### ISSUE TITLE
Review exisiting python-related datapackage projects

### ISSUE THREAD

**Issue by maesbri** [clarity-h2020/qgis3-data-package-builder-plugin#1]
These existing repositories maybe useful for implementing the plugin:
* https://github.com/frictionlessdata/datapackage-py
* https://github.com/centraldedados/datapaka
* http://create.frictionlessdata.io/

**Comment by p-a-s-c-a-l** [comment]
Are there still plans to develop this plug-in and or can we close this issue and archive the repository?

**Comment by maesbri** [comment]
Please, close it. With some many changes in the DataPackage specification this was not really an option anymore (at least for the moment within the context of CLARITY)
